### ISSUE TITLE
Questions about running the_htm_spatial_pooler program

### ISSUE THREAD

**Issue by PerfectVeo** [numenta/htmpapers#15]
I tried running train_sp.py but it didn't work.
I don't know the reason, so I want to ask for help.
Error message:
Traceback (most recent call last):
   File "/disk2/zya/htm_pro/htm-paper/frontiers/the_htm_spatial_pooler_a_neocortical_algorithm_for_online_sparse_distributed_coding/train_sp.py", line 640, in <module>
     Metrics, expName = runSPexperiments(expConfig)
   File "/disk2/zya/htm_pro/htm-paper/frontiers/the_htm_spatial_pooler_a_neocortical_algorithm_for_online_sparse_distributed_coding/train_sp.py", line 553, in runSPexperiments
     reconstructionError(sp, testInputs, activeColumnsCurrentEpoch))
   File "/disk2/zya/env/paper-htm/lib/python2.7/site-packages/htmresearch/frameworks/sp_paper/sp_metrics.py", line 836, in reconstructionError
     numActiveColumns = int(sp._localAreaDensity * sp._numColumns) + 0.0
AttributeError: 'SpatialPooler' object has no attribute '_localAreaDensity'

-

**Comment by PerfectVeo** [comment]
The nupic version in my site-package is 1.0.5. htmresearch version is 0.0.3

**Comment by rhyolight** [comment]
To run these, you'll probably need the latest compiled version of each library:

```
nupic 1.0.6.dev0
nupic.bindings 1.0.7.dev0
```
