### ISSUE TITLE
nab-plot

### ISSUE THREAD

**Issue by Nanakpreet** [numenta/htmpapers#32]
Hi 

I was trying to use nab-plot but it is not getting installed and giving error nab-plot command not found.

**Comment by Nanakpreet** [comment]
/home/docker/NAB# nab-plot realKnownCause/machine_temperature_system_failure.csv --offline --no-xLabel --yLabel="Temperature" --start="2013-12-11 06:10:00"
bash: nab-plot: command not found

I pulled the docker image and then followed the htm papers, clone the nab repository, and installed the requirements.
but nab-plot is not coming with the installation

**Comment by Lizhanqing-2697** [comment]
Traceback (most recent call last):
  File "run.py", line 100, in <module>
    trainer = Trainer(
  File "/home/ly/active_dendrites_enable_multitask_learning/main/trainer.py", line 151, in __init__
    self._algo = CustomMTSAC(
  File "/home/ly/active_dendrites_enable_multitask_learning/main/algorithms/custom_mtsac.py", line 71, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'test_sampler'
